### ISSUE TITLE
Does `active_record_shards` support `rails 5.2.1`?

### ISSUE THREAD

**Issue by lyfudesk** [zendesk/active_record_shards#205]
Does `active_record_shards` support `rails 5.2.1`?

**Comment by bquorning** [comment]
I have still to evaluate https://github.com/zendesk/active_record_shards/pull/191, but I think @bogdan has been using this gem (including the patch from that PR) with Rails 5.2.

**Comment by lyfudesk** [comment]
> I have still to evaluate #191, but I think @bogdan has been using this gem (including the patch from that PR) with Rails 5.2.



Thank you~

**Comment by zhuravel** [comment]
@bquorning 
FYI we’ve been using this branch in production with no issues since the release of Rails 5.2:
https://github.com/talkable/active_record_shards/tree/rails-5.2

It’s `master` from this repository with https://github.com/zendesk/active_record_shards/pull/184 and https://github.com/zendesk/active_record_shards/pull/191 merged.

**Comment by bquorning** [comment]
Thanks @zhuravel, that’s valuable information. I’ll see if I can get those two PRs merged into master soon, so you can start using a proper release :-)

**Comment by zhuravel** [comment]
Thanks @bquorning !
Our test suite passed, now we’ll let it run on staging environment for at least a week :)

**Comment by zhuravel** [comment]
@bquorning Works well on production with Rails 5.2.2. Thanks again :)

**Comment by bquorning** [comment]
Good to hear 👍 You’re welcome.
